name: add labels standardized

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-issue-labels:
    permissions:
      issues: write
    secrets:
      ORG_MEMBERSHIP_TOKEN: ${{ secrets.ORG_MEMBERSHIP_TOKEN }}
      SENZING_MEMBERS: ${{ secrets.SENZING_MEMBERS }}
    uses: senzing-factory/build-resources/.github/workflows/add-labels-to-issue.yaml@v1
