name: add to project gdev

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: add issue to project
    runs-on: ubuntu-latest

    steps:
      - name: assign issue to project
        env:
          GITHUB_TOKEN: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
        uses: senzing-factory/github-action-add-issue-to-project@v1
        with:
          project: "https://github.com/orgs/Senzing/projects/${{ vars.SENZING_PROJECT_GDEV }}"
          column_name: "Backlog"
