name: add to project gdev

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  repository-projects: write

jobs:
  add-to-project:
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project.yaml@v2
    with:
      classic: false
      project-number: ${{ vars.SENZING_PROJECT_GDEV }}
      org: ${{ vars.SENZING_GITHUB_ACCOUNT_NAME }}
