name: move pr to done dependabot

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  repository-projects: write

jobs:
  move-pr-to-done-dependabot:
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/move-pr-to-done-dependabot.yaml@v2
    with:
      project: ${{ vars.SENZING_PROJECT_GDEV }}
